#pragma once
#include <algorithm>
#include <Windows.h>
#include <iostream>
#include <cstdio>
#include <vector>
#include "Offset.h"
#include "Entity.h"
#include "EntityManager.h"
#include "Aimbot.h"
#include "MemoryChanger.h"
#include "Hook.h"
#include "ShellCode.h"
#include "CheatMenu.h"