#pragma once
#include <algorithm>
#include <Windows.h>
#include <iostream>
#include <cstdio>
#include <vector>
#include "Player.h"
#include "MemManager.h"
#include "EntityManager.h"
#include "Aimbot.h"
#include "Target.h"
